options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { any; };

    recursion no;
};

zone "lattice.test" {
    type master;
    file "/etc/bind/zones/db.lattice.test";
    allow-transfer { 172.25.0.3; };
};
