options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { any; };

    recursion no;
};

zone "lattice.test" {
    type slave;
    masters { 172.25.0.2; };
    file "/var/cache/bind/db.lattice.test";
};
